### ISSUE TITLE
Mac OS 版 1.0.3 无法启动。

### ISSUE THREAD

**Issue by bluesky335** [avwo/whistle-client#10]
# Mac OS 版 1.0.3 无法启动。

- MacOS 版本：Sonoma 14.0 (23A344) 
- CPU： Intel 

错误如图

![图片](https://github.com/avwo/whistle-client/assets/13523898/ab68615e-4907-49fe-84f7-a70fb2e92d17)

**Comment by avwo** [comment]
确实有问题，我先把 `1.0.3` 版本回滚，大家先用 1.0.2 版本

**Comment by avwo** [comment]
已解决，下载最新版本即可
