### ISSUE TITLE
Please increase the --max-http-header-size or read args

### ISSUE THREAD

**Issue by lwyj123** [avwo/whistle-client#13]
![image](https://github.com/avwo/whistle-client/assets/9214496/49cb7b88-9115-40f7-8eef-cbdd944e9b0e)

I got this error when debug a project, which have large header...

**Comment by avwo** [comment]
默认 `256k`，可以通过启动参数 `w2 start --max-http-header-size=2560000` 修改

**Comment by avwo** [comment]
> 默认 `256k`，可以通过启动参数 `w2 start --max-http-header-size=2560000` 修改

这个是命令行版本才有的功能，客户端版本我看下怎么加上去

**Comment by avwo** [comment]
下载安装最新版本，新版支持通过左上角 Whistle / Proxy Settings 菜单设置 `--max-http-header-size`
<img width="278" alt="image" src="https://github.com/avwo/whistle-client/assets/11450939/9c86182a-063b-4a20-87b4-752018a7efb2">
