### ISSUE TITLE
[Bug]: Cannot set properties of null (setting 'https')

### ISSUE THREAD

**Issue by firelk** [avwo/whistle-client#14]
<img width="352" alt="Snipaste_2023-11-09_15-13-19" src="https://github.com/avwo/whistle-client/assets/30855929/e5446feb-a2aa-4f38-82e5-e3e51fd6246b">
一直弹框，无法操作

**Comment by avwo** [comment]
看下日志 `~/.WhistleAppData/whistle.log` 是哪个地方报错了

**Comment by avwo** [comment]
或者加 QQ 群 `462558941`
