### ISSUE TITLE
如何安装自己开发的插件

### ISSUE THREAD

**Issue by C370228492** [avwo/whistle-client#16]
在插件根目录 `npm install -g .` 这个方式不生效

**Comment by avwo** [comment]
用这个：https://github.com/avwo/lack

**Comment by C370228492** [comment]
你好, 在[whistle-client](https://github.com/avwo/whistle-client) 的安装插件界面无法指定 npm install  本地文件的方式. 
本地的模块已经通过 `npm install -g . ` 或在 `npm link` 安装或者链接到全局模式, 在whistle-client的plugin上还是没有展示

**Comment by avwo** [comment]
1. 开发可以用 `lack watch`
2. 客户端安装或更新插件在 Plugins 界面上方 Install 按钮

**Comment by C370228492** [comment]
lack watch 可以 .  谢谢谢谢

**Comment by quanquan-dane** [comment]
> 1. 开发可以用 `lack watch`
> 2. 客户端安装或更新插件在 Plugins 界面上方 Install 按钮
win10安装[whistle-client]1.3.3版本在plugin页面点击install无反应

**Comment by avwo** [comment]
@quanquan-dane 已修复，更新下客户端
