### ISSUE TITLE
应用内开机自启

### ISSUE THREAD

**Issue by dcityteg** [avwo/whistle-client#23]
后续能支持开机自启吗？就像命令行的w2 start放进开机启动项。可以加个开关之类的。如果可以的话，非常感谢！

**Comment by avwo** [comment]
可以自己手动配置下
Mac：https://jingyan.baidu.com/article/77b8dc7fbc943c6175eab64e.html
Win：https://answers.microsoft.com/zh-hans/windows/forum/all/%E5%85%B3%E4%BA%8E%E5%A6%82%E4%BD%95%E5%9C%A8windo/5ebcb402-07e3-4975-8a80-61dd9e3be847

**Comment by dcityteg** [comment]
但是这样窗口不是也打开了吗？有没有什么方法可以只开后台服务不开窗口的？谢谢

**Comment by avwo** [comment]
应用场景是什么，是不是可以直接用命令行？

**Comment by dcityteg** [comment]
主要是GO-PROXY-BINGAI的那个项目

**Comment by dcityteg** [comment]
按照WIKI搞得

**Comment by avwo** [comment]
DIY
