### ISSUE TITLE
Consider updating icon design

### ISSUE THREAD

**Issue by 22dm** [avwo/whistle-client#26]
Hello developer, thanks for your great work. However, the icon looks out of place under macOS. Replacing the icon will make Whistle looks better. I've made a version for your reference:

[icon.zip](https://github.com/avwo/whistle-client/files/14501865/icon.zip)

By the way, I think it would look better with a pure white background, as the original gray is too close to the macOS dock background.

![diff](https://github.com/avwo/whistle-client/assets/7871070/d2657141-be33-4170-96e4-5dffbf36cd0e)

**Comment by 22dm** [comment]
Furthermore, the tray icon can also be updated to get a better look whether in dark or light mode.

[tray-icon.zip](https://github.com/avwo/whistle-client/files/14502366/tray-icon.zip)

![diff-tray](https://github.com/avwo/whistle-client/assets/7871070/67481ca9-bb4c-4014-864e-2a1d4793278f)

**Comment by avwo** [comment]
Good job，thanks for providing suggestions and materials, the icons have been updated, please download and install [the latest version](https://github.com/avwo/whistle-client/releases).
