### ISSUE TITLE
能不能增加一个 ctrl+f 查询功能

### ISSUE THREAD

**Issue by niko-liu** [avwo/whistle-client#33]
遇到入参和响应报文字段比较多的时候，需要有一个查询的工具帮助定位参数名

**Comment by avwo** [comment]
Ref https://github.com/avwo/whistle-client/issues/22

**Comment by avwo** [comment]
这个问题终于解决了，更新最新版本的客户端即可：https://github.com/avwo/whistle-client/releases/tag/v1.2.0
