### ISSUE TITLE
如果可以建议使用Chii替换weinre

### ISSUE THREAD

**Issue by gomezshui** [avwo/whistle-client#44]
项目地址：https://github.com/liriliri/chii

相比 weinre 优点：

使用最新的 Chrome DevTools 替换老旧 Web Inspector，体验更好
持续更新维护，Weinre 已不再更新

**Comment by gomezshui** [comment]
项目地址：https://github.com/liriliri/chii

相比 weinre 优点：

使用最新的 Chrome DevTools 替换老旧 Web Inspector，体验更好
持续更新维护，Weinre 已不再更新

**Comment by avwo** [comment]
chii 有插件：https://github.com/liriliri/whistle.chii
