### ISSUE TITLE
在使用windows客户端遇到报错

### ISSUE THREAD

**Issue by codingbylch** [avwo/whistle-client#6]
系统：windows7 
现象：
![6d1da015029fd3cec5df3b1fed1f7ab](https://github.com/avwo/whistle-client/assets/17738529/7821b7f1-9b42-4a82-8daa-1df22eaad877)

似乎是win系统太老，新函数不支持？

**Comment by avwo** [comment]
x系统版本太老 electron 不支持：https://github.com/electron/electron
<img width="869" alt="image" src="https://github.com/avwo/whistle-client/assets/11450939/59f9215c-f606-4f16-94fd-cc9c4a0f5449">
