### ISSUE TITLE
抓包手机出现如下错误：socket disconnected....

### ISSUE THREAD

**Issue by LeetaoGoooo** [avwo/whistle-client#8]
![IMG_B90C9A450D48-1](https://github.com/avwo/whistle-client/assets/10162120/5d3d631a-517c-4001-84f1-ce6b9c8c03b8)

**Comment by avwo** [comment]
看起来像是证书版本问题，换个 Node 版本试试

**Comment by LeetaoGoooo** [comment]
好的～我试一下，感谢
