### ISSUE TITLE
客户端不能开发本地插件吗

### ISSUE THREAD

**Issue by yepochangfeng** [avwo/whistle-client#9]
客户端没有找到安装本地插件的入口，是目前只能安装仓库里面的插件吗？

**Comment by avwo** [comment]
1. 本地开发插件用这个：https://github.com/avwo/lack
2. 安装插件直接在界面 Plugins / 上方 Install 按钮

**Comment by yepochangfeng** [comment]
感谢回复，另外发现一个问题在websocket下Frames/Composer里面点击Send To Server没有执行req.on('sendToServer', (data, isBinary) => {})回调；但是Frames/Composer里面点击Send To Client是有执行 req.on('sendToClient', (data, isBinary) => {})回调的，能否帮忙看下啥原因？

**Comment by avwo** [comment]
<img width="400" alt="image" src="https://github.com/avwo/whistle-client/assets/11450939/da9fe430-f4be-4850-8b38-5fad690706ee">

有没配置这个规则

**Comment by yepochangfeng** [comment]
感谢回复，我刚用别的接口试了试是可以的，可能是我哪里没操作对，我再定位定位。
